# Generated by Django 5.2.1 on 2025-06-10 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CasaEditrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Prodotto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=255)),
                ('prezzo', models.DecimalField(decimal_places=2, max_digits=6)),
                ('casa_editrice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Firmacopie.casaeditrice')),
            ],
        ),
        migrations.CreateModel(
            name='Autore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DisponibilitaAutore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_evento', models.DateField()),
                ('numero_posti', models.PositiveIntegerField()),
                ('autore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Firmacopie.autore')),
            ],
        ),
        migrations.CreateModel(
            name='Firmacopie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('ora', models.TimeField()),
                ('autore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Firmacopie.autore')),
            ],
        ),
        migrations.CreateModel(
            name='FumettoPunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=100)),
                ('prezzo', models.DecimalField(decimal_places=2, max_digits=6)),
                ('genere', models.CharField(max_length=50)),
                ('autore', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Firmacopie.autore')),
            ],
        ),
        migrations.CreateModel(
            name='PrenotazioneFirmacopie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_prenotazione', models.DateTimeField(auto_now_add=True)),
                ('firmacopie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Firmacopie.firmacopie')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruolo', models.CharField(choices=[('utente', 'Utente'), ('autore', 'Autore'), ('manager', 'Manager'), ('casa_editrice', 'Casa Editrice')], default='utente', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('posizione', models.CharField(max_length=255)),
                ('casa_editrice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Firmacopie.casaeditrice')),
            ],
        ),
        migrations.AddField(
            model_name='firmacopie',
            name='stand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Firmacopie.stand'),
        ),
        migrations.CreateModel(
            name='Fumetto',
            fields=[
                ('prodotto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firmacopie.prodotto')),
                ('genere', models.CharField(blank=True, max_length=100)),
                ('autore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Firmacopie.autore')),
            ],
            bases=('Firmacopie.prodotto',),
        ),
        migrations.AddField(
            model_name='firmacopie',
            name='fumetto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Firmacopie.fumetto'),
        ),
    ]
