# Generated by Django 5.2.1 on 2025-06-10 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Firmacopie', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='autore',
            name='casa_editrice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Firmacopie.casaeditrice'),
        ),
        migrations.AddField(
            model_name='casaeditrice',
            name='manager',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='casa_editrice_gestita', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='firmacopie',
            name='casa_editrice',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Firmacopie.casaeditrice'),
        ),
        migrations.AddField(
            model_name='firmacopie',
            name='descrizione',
            field=models.TextField(default='Evento firmacopie ufficiale'),
        ),
        migrations.AddField(
            model_name='firmacopie',
            name='organizzatore',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='eventi_organizzati', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='firmacopie',
            name='data',
            field=models.DateField(default='2025-01-01'),
        ),
        migrations.AlterField(
            model_name='firmacopie',
            name='ora',
            field=models.TimeField(default='12:00'),
        ),
    ]
