# Generated by Django 5.2.1 on 2025-06-11 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Firmacopie', '0002_autore_casa_editrice_casaeditrice_manager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casaeditrice',
            name='autori',
            field=models.ManyToManyField(blank=True, related_name='case_editrici', to='Firmacopie.autore'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ruolo',
            field=models.CharField(choices=[('utente', 'Utente'), ('autore', 'Autore'), ('casa_editrice', 'Casa Editrice')], default='utente', max_length=20),
        ),
    ]
