# Generated by Django 5.2.1 on 2025-06-11 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Firmacopie', '0003_casaeditrice_autori_alter_profile_ruolo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stand',
            name='casa_editrice',
        ),
        migrations.RemoveField(
            model_name='stand',
            name='posizione',
        ),
        migrations.AddField(
            model_name='stand',
            name='disponibile',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='stand',
            name='padiglione',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='stand',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=200)),
                ('orario_inizio', models.DateTimeField()),
                ('orario_fine', models.DateTimeField()),
                ('autore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Firmacopie.autore')),
                ('casa_editrice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Firmacopie.casaeditrice')),
                ('stand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Firmacopie.stand')),
            ],
        ),
    ]
