# Generated by Django 5.2.1 on 2025-06-12 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Firmacopie', '0004_remove_stand_casa_editrice_remove_stand_posizione_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fumettopunta',
            name='genere',
        ),
        migrations.RemoveField(
            model_name='fumettopunta',
            name='prezzo',
        ),
        migrations.RemoveField(
            model_name='fumettopunta',
            name='titolo',
        ),
        migrations.AddField(
            model_name='fumettopunta',
            name='fumetto',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='Firmacopie.fumetto'),
        ),
    ]
