# Generated by Django 5.2.1 on 2025-06-12 09:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Firmacopie', '0005_remove_fumettopunta_genere_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='casaeditrice',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casa_editrice_gestita', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='firmacopie',
            name='casa_editrice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Firmacopie.casaeditrice'),
        ),
        migrations.AlterField(
            model_name='firmacopie',
            name='organizzatore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventi_organizzati', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fumettopunta',
            name='fumetto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Firmacopie.fumetto'),
        ),
    ]
